# Generated by Django 5.0.4 on 2024-04-21 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prerequisiteCode', models.CharField(max_length=20, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='self'))),
                ('instructor', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('scheduleId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='courses.courseschedule'))),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=70)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('roomNo', models.IntegerField()),
            ],
            options={
                'db_table': 'CoursesSchedules',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('courseCode', models.CharField(max_length=20, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'))),
            ],
            options={
                'db_table': 'Enrollments',
                'unique_together': {('studentId', 'courseCode')},
            },
        ),
    ]
