# Generated by Django 5.0.4 on 2024-04-20 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prerequisiteCode', models.CharField(max_length=20, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='self'))),
                ('instructor', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('scheduleId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='courses.courseschedule'))),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=70)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('roomNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('courseId', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'))),
            ],
            options={
                'unique_together': {('studentId', 'courseId')},
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
