# Generated by Django 5.0.4 on 2024-04-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisiteCode',
            new_name='prerequisite_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='scheduleId',
            new_name='schedule_id',
        ),
        migrations.RenameField(
            model_name='courseschedule',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='courseschedule',
            old_name='roomNo',
            new_name='room_no',
        ),
        migrations.RenameField(
            model_name='courseschedule',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='courseCode',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='studentId',
            new_name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_id', 'course_code')},
        ),
    ]
