# Generated by Django 5.0.4 on 2024-04-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_courseschedule_enrollments_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
    ]
